function M = roti(phiDeg,mode)
%3D rotation matrix depending on
%   phiDeg rotation angle in degrees
%   mode   'x' 'y' or 'z' from the formal rotation definition
%   mode   'x4', 'y4', 'z4' for translation compatible 4d matrix

c = cosd(phiDeg);
s = sind(phiDeg);
switch mode
    case 'x'
        M = [1,0,0;...
             0,c,-s;...
             0,s,c];
    case 'y'
        M = [c,0,s;...
            0,1,0;...
            -s,0,c];
    case 'z'
        M = [c,-s,0;...
            s,c,0;...
            0,0,1];
    case 'x4'
        M = [1,0,0,0;...
             0,c,-s,0;...
             0,s,c,0;...
             0,0,0,1];
    case 'y4'
        M = [c,0,s,0;...
            0,1,0,0;...
            -s,0,c,0;...
            0,0,0,1];
    case 'z4'
        M = [c,-s,0,0;...
            s,c,0,0;...
            0,0,1,0;...
            0,0,0,1];
end
